stages:
  - lint
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cashe .npm --prefer-offline


eslint:
  image: node:16.13.1-alpine
  stage: lint
  variables:
    NODE_VERSION: 16.13.1
  script:
    - npm install
    - npm run lint

#prettier:
#  image: node:16.13.1-alpine
#  stage: lint
#  script:
#    - npm install
#    - npm run check:format

deploy:
  image: node:16.13.1-alpine
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - scp .